### ISSUE TITLE
Debug info prints when resizing terminal window

### ISSUE THREAD

**Issue by R-Smith** [gcla/gowid#12]
While resizing a terminal window on Linux, debug info is printing on the bottom of the window.  It seems like 75% of the time the debug info stays printed after the resize is done.  This doesn't happen on Windows.

![resize](https://user-images.githubusercontent.com/22605441/58376405-a32f2380-7f1f-11e9-8a00-e23639b6d7f0.png)

**Comment by gcla** [comment]
Hi, thanks for the report. A few quick questions about your application and its environment - could you check the gowid against which you're building includes this commit?

https://github.com/gcla/gowid/commit/7bbacb2c1cf043a115a9ab2b8b007c6bccc77b13

Unless a log argument is provided to NewApp, the default is now to log to a file named after the application instead of the tty. I think in hindsight having the tty be the default was silly for a tui framework :-/ 

If you have that, could you let me know the terminal program and value of TERM?

Thanks

**Comment by R-Smith** [comment]
Yeah, it looks like I forgot to update this system.  The issue is fixed by that commit.  Thanks!
